apiVersion: v1
kind: Namespace
metadata:
  name: gus-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gus
  namespace: gus-system

spec:
  selector:
    matchLabels:
      app: gus

  template:
    metadata:
      labels:
        app: gus
    spec:


      initContainers:
      - name: init-migrate-seed
        image: gus-image
        command: ['./admin']

      containers:
      - name: gus
        image: gus-image

        ports:
        - name: gus
          containerPort: 3000
        - name: gus-debug
          containerPort: 3010

---

apiVersion: v1
kind: Service
metadata:
  name: gus-service
  namespace: gus-system

spec:
  selector:
    app: gus
