apiVersion: v1
kind: Service
metadata:
  name: gus-service
  namespace: gus-system

spec:
  type: ClusterIP

  ports:
  - name: gus
    port: 3000
    targetPort: gus
  - name: gus-debug
    port: 3010
    targetPort: gus-debug
  - name: metrics
    port: 4000
    targetPort: metrics
  - name: metrics-debug
    port: 4010
    targetPort: metrics-debug
  - name: prometheus
    port: 4020
    targetPort: metrics-prom
