apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gus/
patches:
  - path: ./dev-gus-patch-service.yaml
  - path: ./dev-gus-patch-deploy.yaml

images:
  - name: gus-image
    newName: localhost/gradientsearch/gus
    newTag: 0.0.1
